version: "3.4"
services:
  vpn:
    container_name: vpn
    image: dperson/openvpn-client:latest
    cap_add:
      - net_admin 
    restart: unless-stopped
    volumes:
      - /dev/net:/dev/net:z 
      - /path/to/vpn:/vpn 
    security_opt:
      - label:disable
    ports:
      - 8112:8112  
    command: '-f "" -r 192.168.0.0/16' 

  deluge:
    container_name: deluge
    image: linuxserver/deluge:latest
    restart: unless-stopped
    network_mode: service:vpn 
    depends_on:
      - vpn
    environment:
      - PUID=${PUID} 
      - PGID=${PGID} 
      - TZ=${TZ} 
    volumes:
      - /path/to/downloads:/downloads 
      - ${ROOT}/config/deluge:/config 

  jackett:
    container_name: jackett
    image: linuxserver/jackett:latest
    restart: unless-stopped
    environment:
      - PUID=${PUID} 
      - PGID=${PGID} 
      - TZ=${TZ} 
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /path/to/tornts:/downloads 
      - ${ROOT}/config/jackett:/config 
    ports:
      - 9117:9117

  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr:latest
    restart: unless-stopped
    environment:
      - PUID=${PUID} 
      - PGID=${PGID} 
      - TZ=${TZ} 
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${ROOT}/config/sonarr:/config 
      - /path/to/tv:/tv 
      - /path/to/downloads:/downloads 
    ports:
      - 8989:8989

  radarr:
    container_name: radarr
    image: linuxserver/radarr:latest
    restart: unless-stopped
    environment:
      - PUID=${PUID} 
      - PGID=${PGID} 
      - TZ=${TZ} 
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${ROOT}/config/radarr:/config
      - /path/to/movies:/movies 
      - /path/to/downloads:/downloads 
    ports:
      - 7878:7878

  plex-server:
    container_name: plex-server
    image: ghcr.io/linuxserver/plex
    restart: unless-stopped
    environment:
      - TZ=${TZ} 
      - PLEX_CLAIM=claim-XXXXXXXXXXXXXXXXX
    volumes:
      - ${ROOT}/config/plex/db:/config 
      - /path/to/transcode:/transcode 
      - /path/to/tv:/data/tv 
      - /path/to/movies:/data/movies
    ports:
      - 32400:32400

  bazarr:
    container_name: bazarr
    image: linuxserver/bazarr
    restart: unless-stopped
    environment:
      - PUID=${PUID} 
      - PGID=${PGID} 
      - TZ=${TZ} 
      - UMASK_SET=022 
    volumes:
      - ${ROOT}/config/bazarr:/config 
      - /path/to/movies:/movies 
      - /path/to/tv:/tv 
    ports:
      - 6767:6767

   lidarr:
     image: lscr.io/linuxserver/lidarr:latest
     container_name: lidarr
     environment:
       - PUID=1000
       - PGID=1000
       - TZ=Europe/Amsterdam
     volumes:
       - /path/to/appdata/config:/config
       - /path/to/music:/music
       - /path/to/downloads:/downloads 
     ports:
       - 8686:8686
     restart: unless-stopped
